### PR TITLE
Added a note about using react-error-boundary in client components to…

### PR DESCRIPTION
**Pull request by mrAJAY1**
… clarify restrictions on props.

### CODE REVIEW

**Comment by mrAJAY1** [comment]
@sudheerj I have added the note from docs to clarify the use of 'use client' here. Since the questions are based on reactjs, I think this may cause confusion to beginners, just like it did to me. 🙂

**Comment by sudheerj** [comment]
@mrAJAY1 Can you update use client with a code block?

**Comment by sudheerj** [comment]
Thanks for PR

**Comment by mrAJAY1** [comment]
> @mrAJAY1 Can you update use client with a code block?

Okay!

**Pull request merged**
