### PR TITLE
Bugfix/question missing from table of contents

### PR DESCRIPTION
**Pull request by RobertAndreiGit**
This question [2. What is the history behind React evolution?](https://github.com/sudheerj/reactjs-interview-questions#what-is-the-history-behind-react-evolution)  was missing from the table of contents. Numbering was off/mismatched throughout most of the section because of that

### CODE REVIEW

**Comment by RobertAndreiGit** [comment]
@sudheerj I made this fixing some numbering issues

**Comment by sudheerj** [comment]
@RobertAndreiGit Can you please let me know the exact changes related to TOC. It is quite difficult to understand exact changes because of your multiple commits.

**Comment by RobertAndreiGit** [comment]
@sudheerj fixed the numbering. I believe the description is self-explanatory.

Question [2. What is the history behind React evolution?](https://github.com/sudheerj/reactjs-interview-questions#what-is-the-history-behind-react-evolution) is missing from the ToC and causes numbering mismatches for the rest of the file.

**Comment by RobertAndreiGit** [comment]
You also have both [What are props in React?](https://github.com/sudheerj/reactjs-interview-questions#what-are-props-in-react) and [What is the difference between state and props?](https://github.com/sudheerj/reactjs-interview-questions#what-is-the-difference-between-state-and-props) Numbered with 10 so it appears correct when it's not

**Comment by RobertAndreiGit** [comment]
@sudheerj You can see in the ToC of my PR [here](https://github.com/RobertAndreiGit/reactjs-interview-questions/tree/bugfix/question-missing-from-table-of-contents#what-are-the-major-features-of-react) that those are fixed.

**Comment by sudheerj** [comment]
@RobertAndreiGit It has been fixed already

**Pull request closed without merging**
